### ISSUE TITLE
remove uuid usage from tests/utils/db.js

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/pouchdb-hoodie-unsynced-local-docs#8]
instead of https://github.com/hoodiehq/pouchdb-hoodie-unsynced-local-docs/blob/master/tests/utils/db.js#L11, we can do https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/tests/utils/db.js#L14

For more context, see https://github.com/hoodiehq/pouchdb-hoodie-api/pull/37.

**Comment by zoepage** [comment]
@gr2m fixed + tested with https://github.com/hoodiehq/pouchdb-hoodie-unsynced-local-docs/pull/11

**Comment by gr2m** [comment]
:ok_hand:
